// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UpStock.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614020223_MigracionAuthLogin")]
    partial class MigracionAuthLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UpStock.Models.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assetid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoryid");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codeid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("statusid");

                    b.HasKey("AssetId")
                        .HasName("pk_assets");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("namecategory");

                    b.HasKey("CategoryID")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.Client", b =>
                {
                    b.Property<Guid>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("clientid");

                    b.Property<string>("DniCuit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dnicuit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("ClientID")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.Rental", b =>
                {
                    b.Property<Guid>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rentalid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid")
                        .HasColumnName("clientid");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rentaldate");

                    b.Property<DateTime>("RentalDateExpected")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rentaldateexpected");

                    b.Property<Guid>("StatusID")
                        .HasColumnType("uuid")
                        .HasColumnName("statusid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid?>("client_id")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("status_id")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RentalID")
                        .HasName("pk_rental");

                    b.HasIndex("client_id")
                        .HasDatabaseName("ix_rental_client_id");

                    b.HasIndex("status_id")
                        .HasDatabaseName("ix_rental_status_id");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_rental_user_id");

                    b.ToTable("rental", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.RentalItem", b =>
                {
                    b.Property<Guid>("RentalItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rentalitemid");

                    b.Property<Guid>("AssetID")
                        .HasColumnType("uuid")
                        .HasColumnName("assetid");

                    b.Property<Guid>("RentalID")
                        .HasColumnType("uuid")
                        .HasColumnName("rentalid");

                    b.Property<Guid?>("asset_id")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("rental_id")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_id");

                    b.HasKey("RentalItemID")
                        .HasName("pk_rental_items");

                    b.HasIndex("asset_id")
                        .HasDatabaseName("ix_rental_items_asset_id");

                    b.HasIndex("rental_id")
                        .HasDatabaseName("ix_rental_items_rental_id");

                    b.ToTable("rental_items", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("statusid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("namestatus");

                    b.HasKey("StatusId")
                        .HasName("pk_status");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("UserID")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UpStock.Models.Rental", b =>
                {
                    b.HasOne("UpStock.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("client_id")
                        .HasConstraintName("fk_rental_clients_client_id");

                    b.HasOne("UpStock.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("status_id")
                        .HasConstraintName("fk_rental_status_status_id");

                    b.HasOne("UpStock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .HasConstraintName("fk_rental_users_user_id");

                    b.Navigation("Client");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpStock.Models.RentalItem", b =>
                {
                    b.HasOne("UpStock.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("asset_id")
                        .HasConstraintName("fk_rental_items_assets_asset_id");

                    b.HasOne("UpStock.Models.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("rental_id")
                        .HasConstraintName("fk_rental_items_rental_rental_id");

                    b.Navigation("Asset");

                    b.Navigation("Rental");
                });
#pragma warning restore 612, 618
        }
    }
}
